# Generated by Django 5.2.7 on 2025-12-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_add_stock_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='disabled_reason',
            field=models.CharField(blank=True, choices=[('', 'No reason'), ('sold_out', 'Sold Out'), ('seasonal', 'Seasonal Item'), ('ingredients', 'Missing Ingredients'), ('maintenance', 'Under Maintenance'), ('discontinued', 'Discontinued'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='disabled_reason_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
