# Generated by Django 5.2.7 on 2025-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_add_disabled_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accepts_bank_transfer',
            field=models.BooleanField(default=False, help_text='Accept bank transfers'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_card',
            field=models.BooleanField(default=False, help_text='Accept card payments (Visa, Mastercard)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_cash',
            field=models.BooleanField(default=True, help_text='Accept cash payments'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_mobile_money',
            field=models.BooleanField(default=False, help_text='Accept mobile money (MTN, Airtel, etc.)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_paystack',
            field=models.BooleanField(default=False, help_text='Accept Paystack online payments'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mobile_money_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mobile_money_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
