# Generated by Django 4.2.7 on 2025-10-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='about_title',
            field=models.CharField(blank=True, default='Our Story', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='chef_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='chef_image',
            field=models.ImageField(blank=True, null=True, upload_to='chef_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='chef_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_hero/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hero_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(blank=True, default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(blank=True, default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
