# Generated by Django 5.2.7 on 2025-12-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_about_content_restaurant_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of portions available'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Enable stock tracking for this item'),
        ),
    ]
