# Generated by Django 5.2.7 on 2025-12-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_accepts_bank_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accepts_pos',
            field=models.BooleanField(default=False, help_text='Accept POS terminal payments'),
        ),
    ]
