# Generated by Django 5.2.7 on 2025-12-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_staffinvite_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accent_color',
            field=models.CharField(blank=True, default='#28a745', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='button_style',
            field=models.CharField(choices=[('rounded', 'Rounded'), ('sharp', 'Sharp Corners'), ('pill', 'Pill Shape'), ('outline', 'Outline Only'), ('gradient', 'Gradient')], default='rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for advanced styling'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='font_style',
            field=models.CharField(choices=[('default', 'Default (System)'), ('modern', 'Modern (Poppins)'), ('classic', 'Classic (Playfair Display)'), ('playful', 'Playful (Fredoka)'), ('elegant', 'Elegant (Cormorant Garamond)'), ('bold', 'Bold (Montserrat)')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='header_bg_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='header_style',
            field=models.CharField(choices=[('full_banner', 'Full Banner'), ('compact', 'Compact Header'), ('split', 'Split Layout'), ('video', 'Video Background'), ('slideshow', 'Image Slideshow')], default='full_banner', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='header_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='header_video',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_videos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_layout',
            field=models.CharField(choices=[('grid', 'Grid Cards'), ('list', 'List View'), ('gallery', 'Image Gallery'), ('compact', 'Compact List'), ('magazine', 'Magazine Style')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_about',
            field=models.BooleanField(default=True, help_text='Show about section'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_chef',
            field=models.BooleanField(default=False, help_text='Show chef information'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_contact',
            field=models.BooleanField(default=True, help_text='Show contact section'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_gallery',
            field=models.BooleanField(default=True, help_text='Show gallery section'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_hero',
            field=models.BooleanField(default=True, help_text='Show hero/banner section'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_hours',
            field=models.BooleanField(default=True, help_text='Show opening hours'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_reviews',
            field=models.BooleanField(default=True, help_text='Show reviews section'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_social',
            field=models.BooleanField(default=True, help_text='Show social media links'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='template_style',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('elegant', 'Elegant'), ('fastfood', 'Fast Food')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='text_color',
            field=models.CharField(blank=True, default='#333333', max_length=7),
        ),
    ]
