# Generated by Django 5.2.7 on 2025-12-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='allow_customer_registration',
            field=models.BooleanField(default=True, help_text='Allow new customer signups'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='allow_restaurant_registration',
            field=models.BooleanField(default=True, help_text='Allow new restaurant signups'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Default delivery fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_delivery',
            field=models.BooleanField(default=True, help_text='Allow delivery orders'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_dine_in',
            field=models.BooleanField(default=False, help_text='Allow dine-in orders'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_pickup',
            field=models.BooleanField(default=True, help_text='Allow pickup orders'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_reservations',
            field=models.BooleanField(default=True, help_text='Allow table reservations'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False, help_text='Enable SMS notifications'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_tax',
            field=models.BooleanField(default=False, help_text='Enable tax calculation'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Order amount for free delivery (0 to disable)', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_order_items',
            field=models.PositiveIntegerField(default=50, help_text='Maximum items per order'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='menu_items_per_page',
            field=models.PositiveIntegerField(default=20, help_text='Menu items shown per page'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='order_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes before pending order auto-cancels'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='orders_per_page',
            field=models.PositiveIntegerField(default=10, help_text='Orders shown per page'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='restaurants_per_page',
            field=models.PositiveIntegerField(default=12, help_text='Restaurants shown per page'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='show_out_of_stock',
            field=models.BooleanField(default=True, help_text='Show out-of-stock items'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='tax_name',
            field=models.CharField(default='VAT', help_text='Tax label (e.g., VAT, GST)', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='Tax percentage to apply', max_digits=5),
        ),
    ]
