# Generated by Django 5.2.7 on 2025-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_preferred_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_restaurant',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_answer1',
            field=models.CharField(blank=True, help_text='Answer to first security question', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_answer2',
            field=models.CharField(blank=True, help_text='Answer to second security question', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_answer3',
            field=models.CharField(blank=True, help_text='Answer to third security question', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question1',
            field=models.CharField(blank=True, choices=[('birth_city', 'What city were you born in?'), ('first_school', 'What was the name of your first school?'), ('favorite_color', 'What is your favorite color?'), ('mothers_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?')], help_text='First security question for account recovery', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question2',
            field=models.CharField(blank=True, choices=[('birth_city', 'What city were you born in?'), ('first_school', 'What was the name of your first school?'), ('favorite_color', 'What is your favorite color?'), ('mothers_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?')], help_text='Second security question for account recovery', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question3',
            field=models.CharField(blank=True, choices=[('birth_city', 'What city were you born in?'), ('first_school', 'What was the name of your first school?'), ('favorite_color', 'What is your favorite color?'), ('mothers_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?')], help_text='Third security question for account recovery', max_length=20, null=True),
        ),
    ]
