# Generated by Django 5.2.7 on 2025-12-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_created_at_and_more'),
        ('restaurants', '0008_restaurant_accent_color_restaurant_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_restaurant',
            field=models.ForeignKey(blank=True, help_text='Customer preferred restaurant for quick access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='restaurants.restaurant'),
        ),
    ]
