# Generated by Django 5.2.7 on 2025-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('pos', 'POS Terminal'), ('paystack', 'Paystack Online')], default='card', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('success', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=25),
        ),
    ]
