# Generated by Django 5.2.7 on 2025-12-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
