# Generated by Django 5.2.7 on 2025-10-27 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_groups_and_more'),
        ('restaurants', '0002_restaurant_about_content_restaurant_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_restaurant',
            field=models.ForeignKey(blank=True, help_text="Customer's default/preferred restaurant for direct access", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='restaurants.restaurant'),
        ),
    ]
