# Generated by Django 5.2.7 on 2025-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_saved_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Card (Paystack)'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('pos', 'POS Terminal')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Upload proof of payment for bank transfers', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting Payment Confirmation'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
