# Generated by Django 5.2.7 on 2025-12-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.JSONField(blank=True, help_text='Extra info for delivery orders (name, phone, email, WhatsApp)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Pick Up'), ('delivery', 'Delivery'), ('', 'Not Specified')], default='', max_length=20),
        ),
    ]
